name: meteo_app_notification
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  flutter_riverpod: ^2.6.1
  go_router: ^14.3.0
  geolocator:
  intl: ^0.19.0
  slang_flutter: ^3.32.0
  slang: ^3.32.0
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  url_launcher: ^6.3.1
  timezone: ^0.10.0
  weather_icons: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  slang_build_runner: ^3.32.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
